name: Deploy site

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  doc-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          bundle install
          npm install

      - name: Build main.min.js and run Jekyll
        run: |
          npm run build:js
          bundle exec jekyll build

        # Copy (or touch) other needed files
        # .nojekyll: to tell GH Pages to not rebuild (lol)
        # CNAME: to tell GH Pages about the domain name
      - name: Post-Jekyll build copy files
        run: |
          touch _site/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
