name: Test site build

on:
  pull_request:
    branches: [ master ]

jobs:
  doc-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          bundle install
          npm install

      - name: Build main.min.js and run Jekyll
        run: |
          npm run build:js
          bundle exec jekyll build

      - name: Run Jekyll
        # Build the site using Jekyll
        run: bundle exec jekyll build
